[build]
  command = "git clone https://github.com/flutter/flutter.git --depth 1 --branch stable flutter && flutter/bin/flutter config --enable-web && flutter/bin/flutter pub get && flutter/bin/flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.0"