name: elderly_app
description: Family management app for Alpha Mini robot

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Network
  http: ^1.2.0

  # Storage
  shared_preferences: ^2.3.0

  # State management
  provider: ^6.1.2

  # Date/time
  intl: ^0.19.0

  # Fonts
  google_fonts: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.8

  # Open URLs (payment, links)
  url_launcher: ^6.3.0

  # Speech to text - version mới tương thích Kotlin mới
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true